name: dexter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4

  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  path_provider: ^1.6.0
  flutter_colorpicker: ^0.3.2
  random_color: ^1.0.3
  url_launcher: ^5.4.2
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0
  build_runner: ^1.7.4
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "dev/dexter.png"
  adaptive_icon_background: "#00FFEF"
  adaptive_icon_foreground: "dev/dexter.png"

flutter_launcher_name:
  name: "Dexter"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - assets/cfg/app_settings.config.dart
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # Clock digits
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel/Abel-Regular.ttf
          weight: 400
    # Title
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli/static/Muli-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Muli/static/Muli-Light.ttf
          weight: 300
        - asset: assets/fonts/Muli/static/Muli-Regular.ttf
          weight: 400
        - asset: assets/fonts/Muli/static/Muli-Medium.ttf
          weight: 500
        - asset: assets/fonts/Muli/static/Muli-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Muli/static/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/Muli/static/Muli-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Muli/static/Muli-Black.ttf
          weight: 900
    - family: Encode Sans
      fonts:
        - asset: assets/fonts/EncodeSans/normal/EncodeSansNormal-100-Thin.ttf
          weight: 100
        - asset: assets/fonts/EncodeSans/normal/EncodeSansNormal-200-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/EncodeSans/normal/EncodeSansNormal-300-Light.ttf
          weight: 300
        - asset: assets/fonts/EncodeSans/normal/EncodeSansNormal-400-Regular.ttf
          weight: 400
        - asset: assets/fonts/EncodeSans/normal/EncodeSansNormal-500-Medium.ttf
          weight: 500
        - asset: assets/fonts/EncodeSans/normal/EncodeSansNormal-600-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EncodeSans/normal/EncodeSansNormal-700-Bold.ttf
          weight: 700
        - asset: assets/fonts/EncodeSans/normal/EncodeSansNormal-800-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/EncodeSans/normal/EncodeSansNormal-900-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
